# -*- coding: utf-8 -*-
"""
    generate
    ~~~~~~~~

    A simple script to generate a python dictionary for the emoji's from
    gemoji.

    :copyright: (c) 2015 by sh4nks
    :license: BSD, see LICENSE for more details.
"""
import os
import sys
import argparse
import datetime

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Generates a python dictionary for the emojis from gemoji."
    )

    parser.add_argument(
        '-l', '--lorem',
        help=("Lorem Ipsum"),
        default="dolor",
        required=True
    )

    results = parser.parse_args()

    text = ""
    text += "This file is autogenerated on %s" % (datetime.datetime.utcnow())
    text += "flake8: noqa"
